### ISSUE TITLE
Crose CheckBox text when ticked

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#101]
Make the Checkbox text cross whenever the user clicks on the checkbox.
I have found a cool package for that, it does the crossing animation [animated_line_through](https://pub.dev/packages/animated_line_through)

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/824105b6-151b-44f1-828a-0e2ec044dbed)

**Comment by M4dhav** [comment]
Please Assign

**Comment by guyluz11** [comment]
Done
