### ISSUE TITLE
Open resource link externally button

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#109]
Let’s add a button at the top bar to open the link externally

![IMG_0052](https://github.com/guyluz11/infinite_horizons/assets/9304740/c71b80c3-5b72-4bee-9a18-c1e348d0ea45)

**Comment by Mohit-Joshi-dev** [comment]
I have fixed this issue and rasied a PR for it, please review it. @guyluz11
[https://github.com/guyluz11/infinite_horizons/pull/170](https://github.com/guyluz11/infinite_horizons/pull/170)

**Comment by guyluz11** [comment]
Nice
