### ISSUE TITLE
Timer text above one hour is missing 

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#113]
when choosing a 90m timer the hours character is missing 

![IMG_0055](https://github.com/guyluz11/infinite_horizons/assets/9304740/de5679aa-e197-496c-a9c9-394d397c0eaa)

**Comment by vijaykarthiktk** [comment]
lemme check.

**Comment by guyluz11** [comment]
Open a pr when you are ready

**Comment by guyluz11** [comment]
Actually, this is p0 so needs to get done quickly.

I will work on it next if you didn't started yet

**Comment by vijaykarthiktk** [comment]
wait a min

**Comment by vijaykarthiktk** [comment]
Please check the PR

**Comment by guyluz11** [comment]
Done

Thanks
