### ISSUE TITLE
Tip Description “Tip:” align top

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#120]
![IMG_0096](https://github.com/guyluz11/infinite_horizons/assets/9304740/e7a72f40-89a8-4b70-918c-08d29e55a290)

**Comment by Amitkumarkoli** [comment]
can I help u on this ? 
please assign it to me.

**Comment by guyluz11** [comment]
Yes sure just open PR when you are ready.
No need to get assigned for a small issues.

**Comment by guyluz11** [comment]
Done
