### ISSUE TITLE
Close the keyboard on the home page Timer tab 

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#126]
The home page Text tab opens the keyboard for the user to write.

When swiping to the home page the keyboard should close.

![IMG_0104](https://github.com/guyluz11/infinite_horizons/assets/9304740/1a2cf38b-46d4-49cb-8222-0f14fe318955)

**Comment by vijaykarthiktk** [comment]
lemme check.

**Comment by guyluz11** [comment]
Thanks
