### ISSUE TITLE
Disable back button after "I am ready" button got pressed

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#128]
After pressing the "I am ready" button the confetti animation starts and then the user page gets switched to the next page.
At that time we need to cancel all options of getting to the previous page.
Including the back button (in the image), android back gesture, android back buttons.

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/fc9e421e-0898-4227-8468-0e46bd44cc55)

**Comment by Mohit-Joshi-dev** [comment]
@guyluz11 I would like to contribute here, I am self-assigning this issue to me.

**Comment by Mohit-Joshi-dev** [comment]
I have fixed this issue and rasied a PR for it, please review it. @guyluz11

**Comment by guyluz11** [comment]
Fixed a part of a new flow

**Comment by guyluz11** [comment]
Fixed
