### ISSUE TITLE
ListTileAtom title remove extra space

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#129]
Please remove the extra space

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/7a6cbc1c-e479-4bda-80f2-6228f9b8b692)

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/547579c8-66bf-47ed-a68b-0b36fd212620)

**Comment by azizur-rahaman** [comment]
I want to contribute this, could you please assign me.

**Comment by guyluz11** [comment]
> I want to contribute this, could you please assign me.

Hey @azizur-rahaman 
It looks like this issue got solved I forgot to get closed.
You can find other issues to work on, I suggest #164 as it looks like easy and nice one.

Closing this issue now, thanks.
