### ISSUE TITLE
Radio buttons text area clickable

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#13]
The radio buttons and the text should be clickable as one organism.
Currently you can't click on the text area to toggle the radio button.

<img width="187" alt="image" src="https://github.com/guyluz11/infinite_horizons/assets/9304740/f1092087-239a-45d5-af4d-5b0b26e0b846">

**Comment by M4dhav** [comment]
Can you assign me this issue please?

**Comment by guyluz11** [comment]
Helo helo again :D, good to see you here as well.
Will assign it to you

**Comment by M4dhav** [comment]
I've already submitted a PR for the same, please review and merge

**Comment by guyluz11** [comment]
Thanks for the pr.

Closing
