### ISSUE TITLE
Combine timer and pause continue buttons

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#17]
We can improve the UI by moving the pause continue buttons into the timer

The whole timer will be clickable and there will be a pause/play button in the middle to represent the states

![Screenshot_20240426_140435](https://github.com/guyluz11/infinite_horizons/assets/9304740/6d82ddae-bd26-4bba-a275-a299667313e9)

**Comment by vijaykarthiktk** [comment]
Could you please assign this task to me?

**Comment by guyluz11** [comment]
The whole timer will be clickable and there will be a pause/play button in the middle to represent the states

**Comment by vijaykarthiktk** [comment]
Could you please assign this task to me?

**Comment by guyluz11** [comment]
Just open a pr, that's ok

> Could you please assign this task to me?

**Comment by vijaykarthiktk** [comment]
I've submitted a PR, please review and merge.

**Comment by guyluz11** [comment]
That PR got closed please take a look

**Comment by vijaykarthiktk** [comment]
Yeah sure.

**Comment by vijaykarthiktk** [comment]
How about removing the package from pubspec.yaml and copying the package file to the project directory?

**Comment by guyluz11** [comment]
Hmm that's seems little bit excessive.
Here are couple of options that come to mind.

* Opening pr with the changes to the package
* Finding new package
* Making the whole circle area clickable and when it pause turn the ring color to gray like the clock app in Android but without the pause play buttons
![Screenshot_20240505_115146_Clock](https://github.com/guyluz11/infinite_horizons/assets/9304740/15016806-9595-4489-b519-79b59a37409e)
![Screenshot_20240505_115134_Clock](https://github.com/guyluz11/infinite_horizons/assets/9304740/1a73d9bc-a1e0-4d60-bc4c-d023f8bff5d9)

* Creating a stack layer and position the play pause in a floating way (less recommend)

What do you think?

**Comment by vijaykarthiktk** [comment]
Yeah sure, lemme check it.

**Comment by vijaykarthiktk** [comment]
https://github.com/guyluz11/infinite_horizons/assets/39937989/dc127b31-6af5-4b46-9d93-260d704605f3

what about adding a new package `custom_timer` and building custom timer. I think it works perfectly.
