### ISSUE TITLE
Disable notification icon should contain a slash

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#173]
The disable notification icon should contain a slash

![image](https://github.com/user-attachments/assets/86f6df22-a124-4193-bc94-96dea01a7765)

Should be like the other icons
![image](https://github.com/user-attachments/assets/93ba4785-dbf7-49cc-b124-ea4ef2dff0e8)

**Comment by M4dhav** [comment]
PR Submitted

**Comment by guyluz11** [comment]
Nice
