### ISSUE TITLE
The animated text should start after page fully transitioned

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#175]
We can improve the experience by starting the animated text with a small delay after the page has fully transitioned.

The page itself starts to load before the page transaction is fully completed.

**Comment by M4dhav** [comment]
I can work on this, which text are you talking about specifically

**Comment by guyluz11** [comment]
Second page

**Comment by guyluz11** [comment]
This page got removed with the new UI changes.

Closing as no longer required
