### ISSUE TITLE
Do not disturb

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#18]
That should contain a button to insert the phone into do not disturb mode. 

This way students can learn without any so that and destructions.

**Comment by M4dhav** [comment]
Hey @guyluz11 , which screen do you want the DND button added to?

**Comment by guyluz11** [comment]
Let's add it in the tips page.


![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/2ac31fce-4a25-47ae-b2b9-42016bfca8ec)

**Comment by M4dhav** [comment]
Assign me this issue, I'll get right on this

**Comment by guyluz11** [comment]
Open pr, it's ok

**Comment by guyluz11** [comment]
Done, closing
