### ISSUE TITLE
Readme Google Play link

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#31]
Please add to read me link to Google Play

https://play.google.com/store/apps/details?id=com.haveinfinitehorizons

Make it look like the play store links from here (there are 2)
https://github.com/CyBear-Jinni/cbj_app/blob/master/README.md

And also add the ci tag ang the love open source tag.

**Comment by M4dhav** [comment]
I have finished the requested changes, please approve my other PR and I will submit for this one

**Comment by guyluz11** [comment]
You know that you can open multiple pr right? XD

Just create a new branch and from there you can open the second pr in the same time.

PR got merged so no need for new branch this time :)

**Comment by M4dhav** [comment]
This was something I did not know. I though that all other PRs would contain all the previous commits as well as new changes, messing up the project's commit history

**Comment by guyluz11** [comment]
Ho so good that you are here learning new things :).
Go read on it more it will enrich you.
You probably tried to form from a branch you already committed a change so your new branch contained that history.
You should create the new branch from the original branch you intend it to get merged into.

**Comment by guyluz11** [comment]
Thanks

Closing
