### ISSUE TITLE
Links should get open in webview

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#39]
YouTube videos links should get open in the apps.

Also link to study should get open in browser inside the app.

**Comment by guyluz11** [comment]
It is a little bit tricky, for YouTube we can utilize one of the packages since we don't want it to get open in a browser.
For studies it is a pdf that is getting downloaded when opening so we need to find a way how to view it without the need to download it.

**Comment by M4dhav** [comment]
The PDFs are opening In-app itself for my device, I'm not sure why you're facing the issue, as for Youtube please let me know how you want the UI for videoplayer to look? Should it just route to screen with the player?

**Comment by guyluz11** [comment]
For some phones it get downloaded (maybe because of the default browser), in my case it gets opened in a browser popup on the app and we can't control the top part for example

![tempFileForShare_20240520-152159](https://github.com/guyluz11/infinite_horizons/assets/9304740/32689dd3-5870-471b-aca7-d010ebbdcf19)

But I think currently I am ok with that so let's not touch it.

For YouTube videos please route to a new screen with the video, and design the page as you see fit :)

**Comment by guyluz11** [comment]
Very cool.

Thanks
