### ISSUE TITLE
iOS store link to redme

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#54]
Please add an iOS store link to Redme.
The button should look like this
![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/69578659-e4b1-4ab3-a59d-72413db733ff)
There is a common link for the image, please find it from other open-source projects.

Please ask for the app store link when starting this issue.

**Comment by M4dhav** [comment]
Send me the App Store link please

**Comment by guyluz11** [comment]
> Send me the App Store link please

Here we go

https://apps.apple.com/us/app/infinite-horizons/id6502440548

**Comment by Abhinav-gh** [comment]
Can I work on this issue?

**Comment by guyluz11** [comment]
@Abhinav-gh yep, it is yours :)

**Comment by guyluz11** [comment]
Done
