### ISSUE TITLE
Tip Descritpion tip is out of screen

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#56]
For long tip the text gets out of the screen instead of moving down to the next row

![Screenshot_20240519_211120](https://github.com/guyluz11/infinite_horizons/assets/9304740/d4657dff-cf8c-4c01-9859-3d92dd46c160)

**Comment by M4dhav** [comment]
Assign this please, I'll fix it

**Comment by guyluz11** [comment]
Okay you can work on it, but please create a new PR for that.
Don't combine all changes into one PR, each PR should contain a fixed to one issue.

**Comment by guyluz11** [comment]
Done

Thanks @M4dhav
