### ISSUE TITLE
Improve ProgressIndicatorMolecule design

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#67]
ProgressIndicatorMolecule currently is just a boring progress indicator.
We can easily improve it by switching to [liquid_progress_indicator](https://pub.dev/packages/liquid_progress_indicator)

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/08665f51-b7c2-47fd-9299-a75552165a64)

**Comment by M4dhav** [comment]
I will do this, assign to me please

**Comment by guyluz11** [comment]
No need to assign for that one, just open pr when you are ready

**Comment by guyluz11** [comment]
Can you share the error?

**Comment by M4dhav** [comment]
That's just the thing, It doesn't even show an error. It just does not show a progress bar, even in the counter example app without anything extra.
![image](https://github.com/guyluz11/infinite_horizons/assets/114633095/91ef2a0d-9329-4283-aeca-6b42724ed50f)

The current value is set to 0.25 but as you can see there is no progress bar

**Comment by guyluz11** [comment]
I have checked the package again.

It looks like the example is broken for Android because of the use of old versions, I have opened PR to fix it.

But this is just the example project, the package itself should work with the same code.
Please take another look, maybe you missed something

**Comment by M4dhav** [comment]
I figured it out, the Indicator needs to have a parent Widget with fixed height and width to display properly, which isn't mentioned in the documentation. I will be opening a PR for the same in the package repo soon

**Comment by guyluz11** [comment]
XD Nice work

**Comment by guyluz11** [comment]
Thanks.
Closing
