### ISSUE TITLE
No sound on lock screen

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#69]
The app does not play timer finish sound when the phone is locked (tested on Android).

That should keep in the background even if the phone is locked, and also display the sound of the timer start and timer of finish

**Comment by guyluz11** [comment]
App does not play sound on iOS when the app is minimized

**Comment by M4dhav** [comment]
Can we just use something like wakelock to not let the phone be locked when the app is running instead?

**Comment by guyluz11** [comment]
> Can we just use something like wakelock to not let the phone be locked when the app is running instead?

We already use wakelock but this does not cover it.
Some users want to multitask on the phone, others prefer to save battery, and others prefer not to be distracted by the phone because they can see notifications.

**Comment by M4dhav** [comment]
I think you can try using Isolates for this once

**Comment by guyluz11** [comment]
This could be related to two things

* The logic requires app state change and it by default keeps working in the background. This explains why the timer keeps ticking but stops when there is a state change, so opening the app immediately continues to the next page state.
* There is a need in background processing in which the logic sits in Isolate but just Isolate is not the same.

**Comment by guyluz11** [comment]
It looks like we will have to implement a foreground service.
In ower use case the app is just minimized, I suspect that it requires fewer permissions.

Here are some packages I found in the topic:

[flutter_background_service](https://pub.dev/packages/flutter_background_service)
[flutter_foreground_task](https://pub.dev/packages/flutter_foreground_task)

**Comment by guyluz11** [comment]
Merged, should arrive to the platform in the coming days
