### ISSUE TITLE
Sound effect for the checkbox

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#72]
Let's add a sound effect for the checkbox.
Whenever it gets ticked the sound should start playing

![Screenshot_20240521_212325](https://github.com/guyluz11/infinite_horizons/assets/9304740/03566535-787d-4301-8228-1010afd907d9)

**Comment by M4dhav** [comment]
What Sound Effect do you want to Use?

**Comment by guyluz11** [comment]
I have added to sound effects for this task into the assets/sound_effects folder in dev repo

[straight_line_whoosh_pen_on_paper.wav](https://github.com/guyluz11/infinite_horizons/blob/dev/assets/sound_effects/straight_line_whoosh_pen_on_paper.wav)

[writing_on_a_book_with_a_pen_signing_v.wav](https://github.com/guyluz11/infinite_horizons/blob/dev/assets/sound_effects/writing_on_a_book_with_a_pen_signing_v.wav)

**Comment by guyluz11** [comment]
Done
