### ISSUE TITLE
Settings popup UI improvements

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#77]
The settings popup needs a little UI improvement.

* Add a "Settings" title
* Space between the toggle buttons
* Big space to the close button

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/66a68cde-fa4d-4324-8b00-d3bc9065569c)

**Comment by vijaykarthiktk** [comment]
assign me this.

**Comment by guyluz11** [comment]
> assign me this.

It is yours, no need to assign for this one.
Open a pr when you are ready.

**Comment by guyluz11** [comment]
> assign me this.

@M4dhav got the issue because he was the first to open and Merge a PR.
 We are quick here :D, so now you know for your next issue.

**Comment by M4dhav** [comment]
Yes I opened a PR about 3 days ago

**Comment by guyluz11** [comment]
Done

**Comment by vijaykarthiktk** [comment]
> > assign me this.
> 
> @M4dhav got the issue because he was the first to open and Merge a PR. We are quick here :D, so now you know for your next issue.

Oops! My bad on taking so long with that. Congrats to @M4dhav! Next time for sure.
