### ISSUE TITLE
Tips check box option to open Tip Description

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#80]
Please add an arrow at the end of the line of the tips check box so that it will open the Tip description of the selected tip.
The clickable area for the navigation should only be the arrow icon. 

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/6092437b-0679-4f2d-8a3f-35f5539d1d04)

Please use the same arrow icon from the All Tips page
![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/a72fc46e-f3d8-4605-93a0-879f04627412)

**Comment by vijaykarthiktk** [comment]
please check.

**Comment by guyluz11** [comment]
Thanks

Done
