### ISSUE TITLE
Remove extra radio button padding

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#82]
Remove extra padding for radio buttons

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/81228f2b-79d0-4058-85d1-298cf2104acb)

Decrease spacing from radio buttons to text

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/eee0bc12-8a01-409d-9d7b-15ba07e8a81f)

**Comment by Amitkumarkoli** [comment]
can I help u on this?

**Comment by guyluz11** [comment]
> can I help u on this?

Sure, just open a pr :)

**Comment by guyluz11** [comment]
@Amitkumarkoli This issue was resolved when completing another issue.
https://github.com/guyluz11/infinite_horizons/commit/3a6ce545d70c1b275ee8ada0dfbdef0ca7e19647

You can work on #129 which is the same concept of extra paddings.

Thanks
