### ISSUE TITLE
Entire Area is not clickable in Tip Details Page

### ISSUE THREAD

**Issue by M4dhav** [guyluz11/infinite_horizons#86]
The entire area off the Tip Resource can be made clickable to drop down the resources and Open the links to make for a better UX
![image](https://github.com/guyluz11/infinite_horizons/assets/114633095/1bcb25f2-af8c-4e82-9ca3-57225d5d4b39)

**Comment by guyluz11** [comment]
Sound interesting,
Please make the whole area clickable to expand/shrink the tip and make sure the link button is still opening the link and not shrinking the area

**Comment by guyluz11** [comment]
Completed

Thanks

**Comment by guyluz11** [comment]
@M4dhav will be nice if you can work on #5  or #104
