### ISSUE TITLE
Save selected settings options 

### ISSUE THREAD

**Issue by guyluz11** [guyluz11/infinite_horizons#91]
The selected settings should be saved so that the next time the user opens the app he will get the same settings 

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/ee361bbf-c349-4054-8264-b8f3530ad788)

**Comment by guyluz11** [comment]
@vijaykarthiktk Can you comment on this issue so that I can assign it to you?

**Comment by guyluz11** [comment]
Done

**Comment by vijaykarthiktk** [comment]
> @vijaykarthiktk Can you comment on this issue so that I can assign it to you?

Yeah Sure.
