### ISSUE TITLE
Low Contrast Next Button - UI Improvement

### ISSUE THREAD

**Issue by vijaykarthiktk** [guyluz11/infinite_horizons#95]
### Description
The "Next" button is a bit tricky to see because the background and text color are too similar.  This might make it hard for some folks to find it.
### Additional Information:
I've attached a screenshot of the button (if applicable).
### Impact:
People might miss the button and get stuck!
### Quick Fix:
Change the button color to make it stand out more? Maybe a darker background with lighter text, or vice versa?

![Simulator Screenshot - iPhone 15 Pro Max - 2024-05-28 at 23 14 14](https://github.com/guyluz11/infinite_horizons/assets/39937989/d1cbea1a-8186-49fc-a5ca-667745fe451f)

**Comment by guyluz11** [comment]
The theme colors will change in the future but the contrast between the colors is based on Google [material 3](https://m3.material.io/).
If you can take a look in the [buttons section](https://m3.material.io/components/all-buttons).

I thought that the m3 colors are set by default for the different color types but it looks like it is not the case.

I went through the docks and changed some of the theming.

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/8d420013-7c7d-4b01-b0e8-4aff5d6902fd)

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/04fe51e5-2fcc-4201-ab88-f98e648cb65a)


Thanks

**Comment by guyluz11** [comment]
Done
